# Generated by Django 3.1.5 on 2021-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20210106_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='profile',
            field=models.ImageField(default='pics/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg', upload_to='pics'),
        ),
    ]
