# Generated by Django 3.1.5 on 2021-01-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_teacheruser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='profile',
            field=models.ImageField(default='360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='profile',
            field=models.ImageField(default='360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg', upload_to=''),
        ),
    ]
