# Generated by Django 3.1.5 on 2021-01-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20210107_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='section',
            field=models.IntegerField(default=1),
        ),
    ]
