# Generated by Django 3.1.5 on 2021-01-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_studentquery_studentqueryanswer_teacherqueryanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='section',
            new_name='gender',
        ),
    ]
