# Generated by Django 3.1.5 on 2021-01-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20210112_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='gender',
            field=models.IntegerField(default=1),
        ),
    ]
