# Generated by Django 3.1.5 on 2021-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_teacheruser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='lastloginat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='lastloginat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
