# Generated by Django 3.1.5 on 2021-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20210113_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='lastloginat',
            field=models.CharField(max_length=30),
        ),
    ]
