# Generated by Django 3.1.5 on 2021-01-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_auto_20210116_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheruser',
            old_name='section',
            new_name='sectiont',
        ),
    ]
