# Generated by Django 3.1.5 on 2021-01-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_auto_20210116_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='total_classes_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.teacheruser')),
            ],
        ),
    ]
