# Generated by Django 3.1.5 on 2021-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_auto_20210116_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='section',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='section',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
