# Generated by Django 3.1.5 on 2021-01-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20210117_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='class_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
