# Generated by Django 3.1.5 on 2021-01-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0018_links_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='class_day',
            field=models.DateField(auto_now=True),
        ),
    ]
