# Generated by Django 3.1.5 on 2021-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_links_class_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='class_time',
            field=models.CharField(max_length=10),
        ),
    ]
