# Generated by Django 3.1.5 on 2021-01-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0020_auto_20210118_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='classWiseAttendanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=20)),
                ('class_time', models.CharField(max_length=10)),
                ('get_status', models.CharField(default='attendance not taken', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.studentuser')),
            ],
        ),
    ]
