# Generated by Django 3.1.5 on 2021-01-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_auto_20210118_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwiseattendancestatus',
            name='class_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
