# Generated by Django 3.1.5 on 2021-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0023_auto_20210118_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='class_day',
            field=models.DateField(default='2021-01-19'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='lastloginat',
            field=models.CharField(max_length=30),
        ),
    ]
