# Generated by Django 3.1.5 on 2021-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0024_auto_20210119_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwiseattendancestatus',
            name='section',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='classwiseattendancestatus',
            name='class_time',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='classwiseattendancestatus',
            name='get_status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='classwiseattendancestatus',
            name='subject',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='links',
            name='class_day',
            field=models.DateField(default='2021-01-20'),
        ),
    ]
