# Generated by Django 3.1.5 on 2021-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0026_auto_20210120_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='class_time',
            field=models.CharField(max_length=30),
        ),
    ]
