# Generated by Django 3.1.5 on 2021-01-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0028_auto_20210123_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwiseattendancestatus',
            name='get_status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='links',
            name='class_day',
            field=models.DateField(default='2021-01-24'),
        ),
    ]
