# Generated by Django 3.1.5 on 2021-01-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0030_auto_20210124_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwiseattendancestatus',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='query.teacheruser'),
        ),
    ]
