# Generated by Django 3.1.5 on 2021-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0032_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwiseattendancestatus',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='links',
            name='class_day',
            field=models.DateField(default='2021-01-25'),
        ),
    ]
