# Generated by Django 3.1.5 on 2021-01-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0033_auto_20210125_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquery',
            old_name='datetime',
            new_name='posted_on',
        ),
        migrations.RenameField(
            model_name='studentqueryanswer',
            old_name='datetime',
            new_name='posted_on',
        ),
        migrations.RenameField(
            model_name='teacherqueryanswer',
            old_name='datetime',
            new_name='posted_on',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='query',
        ),
        migrations.AddField(
            model_name='studentquery',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='title',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentqueryanswer',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='query.studentquery'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherQuery',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(default=None)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.teacheruser')),
            ],
        ),
        migrations.AddField(
            model_name='teacherqueryanswer',
            name='title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='query.teacherquery'),
            preserve_default=False,
        ),
    ]
