# Generated by Django 3.1.5 on 2021-01-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0034_auto_20210125_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherqueryanswer',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.teacherquery'),
        ),
    ]
