# Generated by Django 3.1.5 on 2021-01-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('query', '0035_auto_20210125_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='class_day',
            field=models.DateField(default='2021-01-26'),
        ),
        migrations.CreateModel(
            name='QueryBlog',
            fields=[
                ('type', models.CharField(default=None, max_length=30)),
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(default=None)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='QueryAnswerBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=30)),
                ('answer', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.queryblog')),
            ],
        ),
    ]
