# Generated by Django 3.1.5 on 2021-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0036_auto_20210126_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryanswerblog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='queryblog',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='queryanswerblog',
            name='posted_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='queryblog',
            name='posted_by',
            field=models.CharField(max_length=255),
        ),
    ]
