# Generated by Django 3.1.5 on 2021-01-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0037_auto_20210126_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='EventDescription',
            field=models.TextField(default=None),
        ),
    ]
